---
- hosts: control_plane
  become: yes
  roles:
    - k8s_common

  tasks:
    - name: Initialize Kubernetes cluster
      command: >
        kubeadm init 
        --kubernetes-version v1.33.1 
        --pod-network-cidr=192.168.0.0/16 
        --apiserver-advertise-address=0.0.0.0
        --control-plane-endpoint=127.0.0.1
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Configure kubectl for ubuntu user
      shell: |
        mkdir -p /home/ubuntu/.kube
        cp -f /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
        chown ubuntu:ubuntu /home/ubuntu/.kube/config
        
        # 1. Force the server address to local loopback
        sed -i 's/server:.*/server: https:\/\/127.0.0.1:6443/' /home/ubuntu/.kube/config
        
        # 2. Strip out any AWS IAM Authenticator 'exec' blocks that cause the error
        # This deletes the 'exec' line and the subsequent 4 lines of AWS config
        sed -i '/exec:/,+4d' /home/ubuntu/.kube/config
        
        # 3. Wipe the cache to prevent kubectl from remembering old broken endpoints
        rm -rf /home/ubuntu/.kube/cache
      args:
        creates: /home/ubuntu/.kube/config

    - name: Wait for Kubernetes API Server to be ready
      wait_for:
        port: 6443
        host: 127.0.0.1
        delay: 10
        timeout: 120

    - name: Install Calico CNI
      become_user: ubuntu
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
        # Neutralize AWS CLI environment influence
        AWS_ACCESS_KEY_ID: ""
        AWS_SECRET_ACCESS_KEY: ""
        AWS_SESSION_TOKEN: ""
      shell: |
        kubectl apply \
          --server=https://127.0.0.1:6443 \
          --insecure-skip-tls-verify=true \
          --validate=false \
          -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/calico.yaml
      register: cni_result
      until: cni_result is success
      retries: 5
      delay: 15
      changed_when: "'created' in cni_result.stdout or 'configured' in cni_result.stdout"

    - name: Get join command
      command: kubeadm token create --print-join-command
      register: join_cmd

    - name: Share join command in-memory
      add_host:
        name: "K8S_JOIN_HOLDER"
        command: "{{ join_cmd.stdout }}"
