---
- hosts: control_plane
  become: yes
  roles:
    - k8s_common

  tasks:
    - name: Initialize Kubernetes cluster
      # We use the internal Private IP so workers can find the API server
      command: >
        kubeadm init 
        --kubernetes-version v1.33.1 
        --pod-network-cidr=192.168.0.0/16 
        --apiserver-advertise-address={{ ansible_default_ipv4.address }}
        --control-plane-endpoint={{ ansible_default_ipv4.address }}
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Configure and Scrub Kubeconfig
      shell: |
        mkdir -p /home/ubuntu/.kube
        cp -f /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
        chown ubuntu:ubuntu /home/ubuntu/.kube/config
        
        # Remove any AWS IAM 'exec' blocks that cause the authenticator error
        sed -i '/exec:/,+4d' /home/ubuntu/.kube/config
        
        # Ensure the server address in config matches the Private IP
        sed -i 's/server:.*/server: https:\/\/{{ ansible_default_ipv4.address }}:6443/' /home/ubuntu/.kube/config
        
        rm -rf /home/ubuntu/.kube/cache
      # No 'creates' here so it always fixes the config

    - name: Wait for Kubernetes API Server to be ready
      wait_for:
        port: 6443
        host: "{{ ansible_default_ipv4.address }}"
        delay: 10
        timeout: 120

    - name: Install Calico CNI
      become_user: ubuntu
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
        AWS_ACCESS_KEY_ID: ""
        AWS_SECRET_ACCESS_KEY: ""
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/calico.yaml --validate=false
      register: cni_result
      until: cni_result is success
      retries: 5
      delay: 15

    - name: Get join command
      command: kubeadm token create --print-join-command
      register: join_cmd

    - name: Share join command in-memory
      add_host:
        name: "K8S_JOIN_HOLDER"
        command: "{{ join_cmd.stdout }}"
