---
- name: Configure Kubernetes workers
  hosts: workers
  become: yes
  vars:
    containerd_config_path: /etc/containerd/config.toml

  roles:
    - role: k8s_common

  tasks:
    - name: Get join command from control plane
      delegate_to: control-plane-01
      run_once: true
      ansible.builtin.shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command as a fact
      ansible.builtin.set_fact:
        kubernetes_join_command: "{{ join_command_raw.stdout }}"

    - name: Execute Kubernetes join command
      ansible.builtin.shell: "{{ kubernetes_join_command }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
      async: 60       # Run for up to 60 seconds
      poll: 5         # Check status every 5 seconds
      register: join_result
      # This handles the SSH drop gracefully

    - name: Wait for workers to settle and SSH to return
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 60

    - name: Ensure kubelet is running and enabled
      ansible.builtin.systemd:
        name: kubelet
        state: started
        enabled: yes
