---
- name: Configure Kubernetes workers
  hosts: workers
  become: yes
  vars:
    containerd_config_path: /etc/containerd/config.toml

  roles:
    - role: k8s_common

  tasks:
    - name: Get join command from control plane
      # We use the name defined in your Terraform-generated inventory.ini
      delegate_to: control-plane-01
      run_once: true
      ansible.builtin.shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command as a fact
      ansible.builtin.set_fact:
        kubernetes_join_command: "{{ join_command_raw.stdout }}"
      delegate_to: "{{ item }}"
      delegate_facts: true
      with_items: "{{ groups['workers'] }}"

    - name: Execute Kubernetes join command
      ansible.builtin.shell: "{{ kubernetes_join_command }}"
      become: yes
      args:
        # This 'creates' check prevents the worker from trying to join twice
        creates: /etc/kubernetes/kubelet.conf