---
- name: Configure Kubernetes workers
  hosts: workers
  become: yes
  roles:
    - role: k8s_common

  tasks:
    - name: Get join command from memory
      set_fact:
        kubernetes_join_command: "{{ hostvars['K8S_JOIN_HOLDER']['command'] }}"

    - name: Reset kubeadm to clear previous failed attempts
      command: kubeadm reset -f
      args:
        removes: /etc/kubernetes/kubelet.conf
      ignore_errors: yes

    - name: Execute Kubernetes join command
      shell: "{{ kubernetes_join_command }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
      async: 180
      poll: 10

    - name: Ensure kubelet is running and enabled
      systemd:
        name: kubelet
        state: started
        enabled: yes
