---
- name: Configure Kubernetes workers
  hosts: workers
  become: yes
  vars:
    containerd_config_path: /etc/containerd/config.toml

  roles:
    - role: k8s_common

  tasks:
    - name: Get join command from control plane
      delegate_to: control-plane-01
      run_once: true
      ansible.builtin.shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command as a fact for all workers
      ansible.builtin.set_fact:
        kubernetes_join_command: "{{ join_command_raw.stdout }}"

    - name: Wait for containerd to be fully active
      ansible.builtin.pause:
        seconds: 5

    - name: Execute Kubernetes join command
      ansible.builtin.shell: "{{ kubernetes_join_command }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
      register: join_result
      # Optional: Helpful for debugging if the join fails
      failed_when: 
        - join_result.rc != 0 
        - "'already exists' not in join_result.stderr"

    - name: Verify kubelet is running
      ansible.builtin.systemd:
        name: kubelet
        state: started
        enabled: yes
